PI24-19 signale graphiquement l'etat de la cafetiere
btssn-lasalle-84/pikawa-2024 pull request #20
Opened 2024-05-27 13:00 UTC by Nmdoiouhoma

J'ai un doute concernant l'alerte de l'absence ou presence de capsule en fonction de etatMagasin() 
est une bonne idée d'ajouter des icones dans l'ecran MagasinsCapsules pour chaque rangée indiquant son etat ?

2024-05-27 16:21 UTC, tvaira commented
> J'ai un doute concernant l'alerte de l'absence ou presence de capsule en fonction de etatMagasin() est une bonne idée d'ajouter des icones dans l'ecran MagasinsCapsules pour chaque rangée indiquant son etat ?

Oui peut-être mais ce n'est pas urgent. Par contre, tu peux ajouter la gestion des erreurs dans la réception de la trame EtatPreparation.

2024-05-31 15:02 UTC, tvaira requested changes

2024-05-31 15:02 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +    // @todo recuperer la derniere capsule
Je t'ai mis les todos mais, à l'avenir, travaille sur les fonctions demandées.

2024-06-03 13:15 UTC, tvaira requested changes

2024-06-03 13:15 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +        qDebug() << "Préparation du café en cours...";
On ne veut pas de _debug_ comme cela ! IL FAUT TOUJOURS LA METHODE, LA LIGNE et LE OU LES VARIABLES (NOM + VALEUR) !!! Tu n'as qu'à regarder les autres _debug_.

2024-06-03 13:15 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +        qDebug() << "Erreur: Type de café invalide.";
Et alors ?! Quelle est la valeur du type ?

2024-06-03 13:15 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
>      }
Tu as un gros problème d'indentation !!! Il faut utiliser `clang-format` et ce n'est pas négociable.

2024-06-03 13:15 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +                                   QString(typeDernierCafe) + TRAME_SEPARATEUR +
`typeDernierCafe`  est déjà un `QString` !

2024-06-03 13:15 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +    int pasProgression = 100 * DUREE_PROGRESSION / dureeTotalePreparation;
Il faut mettre des parenthèses.

2024-06-04 14:13 UTC, Nmdoiouhoma commented
J'ai ajouté un LCDNumber dans l'ecran MagasinCapsule qui est initialisé avec tel quel : ` #define NB_CAPSULE_MAX           32` , `ui->capsuleTotalRestantes->display(NB_CAPSULE_MAX);` mais je pense qu'il faudrait l'initialité avec la base de donnée en parcourant chaque quantite mais je me demande comment faire ?

2024-06-04 14:59 UTC, tvaira requested changes

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/GestionMagasin.h
> +#define NB_CAPSULE_MAX           32
Non !!! c'est : `#define NB_CAPSULE_MAX (NB_COLONNES_CAPSULE * NB_CAPSULE_PAR_COLONNE)`

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/GestionMagasin.h
> +    int                  quantiteCapsuleMax;
Inutile ! Tu as un `define` pour cela. Par contre, il te faut un attribut `quantiteCapsuleRestante`

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +                                   TRAME_SEPARATEUR + QString(typeDernierCafe) + TRAME_SEPARATEUR +
Je t'ai déjà fait remarquer que `typeDernierCafe` est DÉJÀ un `QString` !!!

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +        qDebug() << Q_FUNC_INFO << "Erreur: Type de café invalide." << typeDernierCafe;
Tu as du mal à comprendre le _debug_ !!! On ne fait pas de phrase dans les _debugs_ !!! 

```cpp
qDebug() << Q_FUNC_INFO << "Erreur" << "typeDernierCafe" << typeDernierCafe;
```

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +    listeLCDNumberCapsules.push_back(ui->capsuleTotalRestantes);
Non ! Il n'a rien à voir !!! Il faut le gérer à part et pas dans le `QVector`.

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +    ui->capsuleTotalRestantes->display(NB_CAPSULE_MAX);
Non, il te faut calculer la quantité restante du magasin.

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.cpp
> +void IhmPikawa::initialiserCapsulesRestantesTotal()
Non ! Ce n'est pas initialiser mais **calculer** !

2024-06-04 14:59 UTC, tvaira commented on pikawa-rpi/ihmpikawa.h
> +    void initialiserCapsulesRestantesTotal();
Non ! Ce n'est pas initialiser mais calculer !

2024-06-04 15:04 UTC, tvaira commented
> J'ai ajouté un LCDNumber dans l'ecran MagasinsCapsule qui est initialisé avec tel quel : ` #define NB_CAPSULE_MAX 32` , `ui->capsuleTotalRestantes->display(NB_CAPSULE_MAX);` mais je pense qu'il faudrait l'initialisé avec la base de donnée en parcourant chaque champs quantite de la table StockMagasin mais je me demande comment faire ?

Le `stock` est un `QVector` de la classe `GestionMgasin`. Tu ajoutes une méthode qui calcule et retourne le nombre de capsules dans le magasin. Tu dois faire une boucle du `QVector` qui récupère le champ `QUANTITE_CAPSULE_STOCK`, le convertit en `int` et l'additionne !

Par contre, tu dois te secouer car il te reste des fonctionnalités importantes du cahier des charges que tu n'as pas encore faites !!!

2024-06-05 13:37 UTC, tvaira approved these changes

2024-06-05 13:37 UTC, merged